//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CSharp_Console_RPS_Game {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CSharp_Console_RPS_Game.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///    88
        ///  ,d88
        ///888888
        ///    88
        ///    88
        ///    88
        ///    88
        ///    88
        ///
        ///.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.d888b.
        ///VP  `8D
        ///   odD&apos;
        /// .88&apos;
        ///j88.
        ///888888D
        ///.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d8888b.
        ///VP  `8D
        ///  oooY&apos;
        ///  ~~~b.
        ///db   8D
        ///Y8888P&apos;
        ///.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.IO.UnmanagedMemoryStream similar to System.IO.MemoryStream.
        /// </summary>
        internal static System.IO.UnmanagedMemoryStream bg_music {
            get {
                return ResourceManager.GetStream("bg_music", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d8888b. db    db d88888b
        ///88  `8D `8b  d8&apos; 88&apos;
        ///88oooY&apos;  `8bd8&apos;  88ooooo
        ///88~~~b.    88    88~~~~~
        ///88   8D    88    88.
        ///Y8888P&apos;    YP    Y88888P
        ///.
        /// </summary>
        internal static string Bye {
            get {
                return ResourceManager.GetString("Bye", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.o88b.  .d88b.  d8b   db  .o88b. db      db    db .d8888. d888888b  .d88b.  d8b   db
        ///d8P  Y8 .8P  Y8. 888o  88 d8P  Y8 88      88    88 88&apos;  YP   `88&apos;   .8P  Y8. 888o  88
        ///8P      88    88 88V8o 88 8P      88      88    88 `8bo.      88    88    88 88V8o 88
        ///8b      88    88 88 V8o88 8b      88      88    88   `Y8b.    88    88    88 88 V8o88
        ///Y8b  d8 `8b  d8&apos; 88  V888 Y8b  d8 88booo. 88b  d88 db   8D   .88.   `8b  d8&apos; 88  V888
        /// `Y88P&apos;  `Y88P&apos;  VP   V8P  `Y88P&apos; Y88888P ~Y8888P&apos; `8888Y&apos; Y888888P  `Y88P&apos;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Conclusion {
            get {
                return ResourceManager.GetString("Conclusion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///db   db d888888b d8b   db d888888b
        ///88   88   `88&apos;   888o  88 `~~88~~&apos;
        ///88ooo88    88    88V8o 88    88
        ///88~~~88    88    88 V8o88    88
        ///88   88   .88.   88  V888    88
        ///YP   YP Y888888P VP   V8P    YP
        ///.
        /// </summary>
        internal static string Hint {
            get {
                return ResourceManager.GetString("Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d888888b d8b   db db    db  .d8b.  db      d888888b d8888b.
        ///  `88&apos;   888o  88 88    88 d8&apos; `8b 88        `88&apos;   88  `8D
        ///   88    88V8o 88 Y8    8P 88ooo88 88         88    88   88
        ///   88    88 V8o88 `8b  d8&apos; 88~~~88 88         88    88   88
        ///  .88.   88  V888  `8bd8&apos;  88   88 88booo.   .88.   88  .8D
        ///Y888888P VP   V8P    YP    YP   YP Y88888P Y888888P Y8888D&apos;
        ///.
        /// </summary>
        internal static string Invalid {
            get {
                return ResourceManager.GetString("Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d8888b.  .d8b.  d8888b. d88888b d8888b.
        ///88  `8D d8&apos; `8b 88  `8D 88&apos;     88  `8D
        ///88oodD&apos; 88ooo88 88oodD&apos; 88ooooo 88oobY&apos;
        ///88~~~   88~~~88 88~~~   88~~~~~ 88`8b
        ///88      88   88 88      88.     88 `88.
        ///88      YP   YP 88      Y88888P 88   YD
        ///.
        /// </summary>
        internal static string Paper {
            get {
                return ResourceManager.GetString("Paper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d888b  d88888b d888888b      d8888b. d88888b  .d8b.  d8888b. db    db
        ///88&apos; Y8b 88&apos;     `~~88~~&apos;      88  `8D 88&apos;     d8&apos; `8b 88  `8D `8b  d8&apos;
        ///88      88ooooo    88         88oobY&apos; 88ooooo 88ooo88 88   88  `8bd8&apos;
        ///88  ooo 88~~~~~    88         88`8b   88~~~~~ 88~~~88 88   88    88
        ///88. ~8~ 88.        88         88 `88. 88.     88   88 88  .8D    88
        /// Y888P  Y88888P    YP         88   YD Y88888P YP   YP Y8888D&apos;    YP
        ///.
        /// </summary>
        internal static string Ready {
            get {
                return ResourceManager.GetString("Ready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///88888888ba   88888888888  ad88888ba   88        88  88      888888888888
        ///88      &quot;8b  88          d8&quot;     &quot;8b  88        88  88           88
        ///88      ,8P  88          Y8,          88        88  88           88
        ///88aaaaaa8P&apos;  88aaaaa     `Y8aaaaa,    88        88  88           88
        ///88&quot;&quot;&quot;&quot;88&apos;    88&quot;&quot;&quot;&quot;&quot;       `&quot;&quot;&quot;&quot;&quot;8b,  88        88  88           88
        ///88    `8b    88                  `8b  88        88  88           88
        ///88     `8b   88          Y8a     a8P  Y8a.    .a8P  88           88
        ///88      `8b  888888888 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///d8888b.  .d88b.   .o88b. db   dD
        ///88  `8D .8P  Y8. d8P  Y8 88 ,8P&apos;
        ///88oobY&apos; 88    88 8P      88,8P
        ///88`8b   88    88 8b      88`8b
        ///88 `88. `8b  d8&apos; Y8b  d8 88 `88.
        ///88   YD  `Y88P&apos;   `Y88P&apos; YP   YD
        ///.
        /// </summary>
        internal static string Rock {
            get {
                return ResourceManager.GetString("Rock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.d8888.  .o88b. d888888b .d8888. .d8888.  .d88b.  d8888b. .d8888.
        ///88&apos;  YP d8P  Y8   `88&apos;   88&apos;  YP 88&apos;  YP .8P  Y8. 88  `8D 88&apos;  YP
        ///`8bo.   8P         88    `8bo.   `8bo.   88    88 88oobY&apos; `8bo.
        ///  `Y8b. 8b         88      `Y8b.   `Y8b. 88    88 88`8b     `Y8b.
        ///db   8D Y8b  d8   .88.   db   8D db   8D `8b  d8&apos; 88 `88. db   8D
        ///`8888Y&apos;  `Y88P&apos; Y888888P `8888Y&apos; `8888Y&apos;  `Y88P&apos;  88   YD `8888Y&apos;
        ///.
        /// </summary>
        internal static string Scissors {
            get {
                return ResourceManager.GetString("Scissors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///.d8888. d88888b d888888b db    db d8888b.
        ///88&apos;  YP 88&apos;     `~~88~~&apos; 88    88 88  `8D
        ///`8bo.   88ooooo    88    88    88 88oodD&apos;
        ///  `Y8b. 88~~~~~    88    88    88 88~~~
        ///db   8D 88.        88    88b  d88 88
        ///`8888Y&apos; Y88888P    YP    ~Y8888P&apos; 88
        ///.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
    }
}
